/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.MasterOrderList;
import Business.PersonDirectory;
import Business.SupplierDirectory;
import Business.UserAccount;
import Business.UserDirectory;
import UserInterface.AdministrativeRole.AdminWorkAreaJPanel;
import UserInterface.CustomerRole.CustomerWorkAreaJPanel;
import UserInterface.SupplierRole.LoginSupplierJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepak
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    SupplierDirectory supplierDir;
    private Business business;
    private SupplierDirectory supplierDirectory;
    private UserDirectory userAccountDirectory;
    private MasterOrderList masterOrderList;
    private PersonDirectory personDirectory;
    
    public MainJFrame() {
        initComponents();
        supplierDir = new SupplierDirectory();
        business=new Business();
        
        userAccountDirectory = business.getUserAccountDirectory();
        supplierDirectory=business.getSupplierDirectory();
        masterOrderList=business.getMasterOrderList();
        personDirectory=business.getPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordUsernamejPasswordField1 = new javax.swing.JPasswordField();
        LoginjButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(UsernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(PasswordUsernamejPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));

        LoginjButton1.setText("Login");
        LoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(LoginjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setPreferredSize(new java.awt.Dimension(500, 500));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginjButton1ActionPerformed
        userProcessContainer.removeAll();
        
        String username = UsernamejTextField1.getText();
        String password = String.valueOf(PasswordUsernamejPasswordField1.getPassword());
        
        UserAccount userAccount = userAccountDirectory.authenticate(username, password);
        if(userAccount==null){
            jLabel3.setText("Invalid Credential");
            return;
        }
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        JPanel nextPanel = null;
        String panelName = null;
        
        if(userAccount.getRole().equals(userAccountDirectory.ADMIN_ROLE)){
            nextPanel = new AdminWorkAreaJPanel(userProcessContainer, supplierDir,userAccountDirectory, personDirectory);
            panelName = "adminWorkAreaJPanel";
            layout.next(userProcessContainer);
        }else if(userAccount.getRole().equals(userAccountDirectory.CUSTOMER_ROLE)){
            nextPanel = new CustomerWorkAreaJPanel(userProcessContainer, supplierDir,masterOrderList);
            panelName = "customerWorkAreaJPanel";
        } else if(userAccount.getRole().equals(userAccountDirectory.SUPPLIER_ROLE)){
            nextPanel = new LoginSupplierJPanel(userProcessContainer, supplierDirectory);
            panelName = "LogonSupplierJPanel";
        }
        userProcessContainer.add(panelName, nextPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_LoginjButton1ActionPerformed
        //end of Login Button
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginjButton1;
    private javax.swing.JPasswordField PasswordUsernamejPasswordField1;
    private javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
