/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package UserInterface.CustomerRole;

import Business.MasterOrderList;
import Business.Order;
import Business.OrderItem;
import Business.Product;
import Business.Supplier;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Deepak
 */
public class BrowseProductsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    SupplierDirectory supplierDir;
   private MasterOrderList masterOrderList;
    private Order order;
   

    /** Creates new form BrowseProducts */
    public BrowseProductsJPanel(JPanel userProcessContainer, SupplierDirectory supplierDir, MasterOrderList masterOrderList1) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDir = supplierDir;
        this.masterOrderList=masterOrderList1;
      
        order = new Order(); //just a dummy object is created here for this panel only. This order object won't get added to masterorderlist
        
        suppComboBox1.removeAllItems();
        for(Supplier s: supplierDir.getSupplierList()){
            suppComboBox1.addItem(s);
        }
    }

    private void populateOrderItemTable(){
        DefaultTableModel model = (DefaultTableModel)OrderItemjTable1.getModel();
        model.setRowCount(0);
        
        for(OrderItem oi : order.getOrderItemList()){
            Object[] row = new Object[2];
            row[0] = oi.getProduct().getName();
            row[1] = oi.getQuantity();
            model.addRow(row);
        }
    }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTable1 = new javax.swing.JTable();
        suppComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        viewProdjButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderItemjTable1 = new javax.swing.JTable();
        QuantityjSpinner1 = new javax.swing.JSpinner();
        AddToCartjButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CheckoutjButton2 = new javax.swing.JButton();
        BackjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 511));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Model No.", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable1);
        productTable1.getColumnModel().getColumn(0).setResizable(false);
        productTable1.getColumnModel().getColumn(1).setResizable(false);
        productTable1.getColumnModel().getColumn(2).setResizable(false);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 390, 130));

        suppComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppComboBox1ActionPerformed(evt);
            }
        });
        add(suppComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Supplier Product Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Browse Products");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, -1));

        viewProdjButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewProdjButton2.setText("View Product Detail");
        viewProdjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton2ActionPerformed(evt);
            }
        });
        add(viewProdjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 210, -1));

        OrderItemjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(OrderItemjTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 400, 120));
        add(QuantityjSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        AddToCartjButton1.setText("Add to Cart");
        AddToCartjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartjButton1ActionPerformed(evt);
            }
        });
        add(AddToCartjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel4.setText("Quantity");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        CheckoutjButton2.setText("Checkout");
        CheckoutjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutjButton2ActionPerformed(evt);
            }
        });
        add(CheckoutjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        BackjButton1.setText("<<Back");
        add(BackjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void suppComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppComboBox1ActionPerformed
        
        
        Supplier selectedSupplier = (Supplier) suppComboBox1.getSelectedItem();
        if(selectedSupplier == null){
            return;
        }
        
        int rowCount = productTable1.getRowCount();
        for(int i=rowCount-1; i>=0; i--){
            ((DefaultTableModel)productTable1.getModel()).removeRow(i);
        }
        
        
        for(Product p: selectedSupplier.getProductCatalog().getProductList()){
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getProductId();
            row[2] = p.getPrice();
            
            ((DefaultTableModel)productTable1.getModel()).addRow(row);  
        }
        
    }//GEN-LAST:event_suppComboBox1ActionPerformed

    
    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void viewProdjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton2ActionPerformed
        
        int selectedRow = productTable1.getSelectedRow();
        if(selectedRow < 0){
            return;
        }
        Product product = (Product) productTable1.getValueAt(selectedRow, 0);
        
        ViewProductDetailJPanel vjp = new ViewProductDetailJPanel(userProcessContainer, product);
        userProcessContainer.add("ViewProductDetailJPanel", vjp);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_viewProdjButton2ActionPerformed

    private void AddToCartjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartjButton1ActionPerformed
        int selectedRow = productTable1.getSelectedRow();
        if(selectedRow<0){
            return;
        }
        
        Product product = (Product) productTable1.getValueAt(selectedRow, 0);
        int quantity = (int) QuantityjSpinner1.getValue();
        
        OrderItem orderItem = order.createAndAddOrderItem();
        orderItem.setProduct(product);
        orderItem.setQuantity(quantity);
        
        populateOrderItemTable();
    }//GEN-LAST:event_AddToCartjButton1ActionPerformed

    private void CheckoutjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutjButton2ActionPerformed
        masterOrderList.addOrder(order);
    }//GEN-LAST:event_CheckoutjButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartjButton1;
    private javax.swing.JButton BackjButton1;
    private javax.swing.JButton CheckoutjButton2;
    private javax.swing.JTable OrderItemjTable1;
    private javax.swing.JSpinner QuantityjSpinner1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productTable1;
    private javax.swing.JComboBox suppComboBox1;
    private javax.swing.JButton viewProdjButton2;
    // End of variables declaration//GEN-END:variables
}
